using System;

namespace LOR_XML
{
	public enum DialogType
	{
		START_BATTLE,
		BATTLE_VICTORY,
		DEATH,
		COLLEAGUE_DEATH,
		KILLS_OPPONENT,
		EMOTION_BODY_AROUSAL,
		EMOTION_BODY_COLLAPSE,
		EMOTION_HEAD_AROUSAL,
		EMOTION_HEAD_COLLAPSE,
		EMOTION_HEART_AROUSAL,
		EMOTION_HEART_COLLAPSE,
		ENCOUNTERS_OPPONENT,
		SPECIAL_EVENT,
		ERROR
	}
}
